name: Deploy main to prod when tokens are updated

on:
  push:
    branches: [main]
    paths:
      - "packages/designtokens/tokens/**"

jobs:
  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          always-auth: true

      - name: Yarn install
        run: yarn install

      - name: Build and export designtokens
        run: yarn workspace designtokens run build:export

      - name: Build Storybook
        run: export NODE_OPTIONS=--openssl-legacy-provider && yarn workspace designsystem run build:storybook

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: "thawi"
          ALIAS_DOMAINS: |
            play-together-designsystem.vercel.app
            {USER}-{REPO}-{SHA}.vercel.app
          PRODUCTION: true
